language: c

os: linux
dist: trusty
# Use full depth for SonarCLoud
git:
  depth: false 

install:
  - sudo pip install gcovr
  - sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib && sudo apt-get install -qq
  - sudo apt-get install -qq pvs-studio 
  - gem install ceedling

script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - ceedling test:all
  - ceedling gcov:all utils:gcov
  - gcov  -b -c build/gcov/out/*.gcno
  - sonar-scanner -Dsonar.projectVersion=$TRAVIS_TAG

addons:
  sonarcloud:
    organization: "ojousima"
    projectKey: "ojousima_ojousima.npa-700.c"